"""add country category source_url to documents

Revision ID: 70c8891613ca
Revises: e30312209438
Create Date: 2026-09-12 12:54:52.749145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70c8891613ca'
down_revision: Union[str, Sequence[str], None] = 'e30312209438'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('country', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('category', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('source_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'source_url')
    op.drop_column('documents', 'category')
    op.drop_column('documents', 'country')
    # ### end Alembic commands ###
